name: Publish feature
on:
  push:
    branches:
      - main
  workflow_dispatch:
  release:
    types: [published]
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: devcontainers-community/publish-feature@v1
        with:
          path: ./src/nekronos-workbench
          image: ghcr.io/${{ github.repository }}/*
